name = "Friends with Cogs"
author = "Friends Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df8d51369652dada726e01fc619752a675a59ad799ecaf4571eb758edf9a873a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
