name = "Friends with Cogs"
author = "Friends Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71d55e40a3bff1612304ac304a9eaf83d19525132ff0b04002bdc7b5ac94b81f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
