name = "Friends with Cogs"
author = "Friends Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42ad06c1b2f538e47a483f438389ee2be30d7046ede1888575ca1f71b393f3c3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
